#!/bin/bash
if [ $2 ]
  then
   INSTALL_DIR="$2"
   FORCE_INSTALL="+force_install_dir"
fi

/home/steam/steamcmd/steamcmd.sh  +login anonymous $FORCE_INSTALL $INSTALL_DIR  +app_update $1 validate +quit

while [ $? -ne 0 ]
do
echo "Install failed... Retrying"
/home/steam/steamcmd/steamcmd.sh  +login anonymous $FORCE_INSTALL $INSTALL_DIR +app_update $1 validate +quit
done

echo "Finished!"
